// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPaf12pJLZNFhc48dTegWhvZHHhErB-cM',
    appId: '1:357054968732:web:1dab4af2b0a5f88dc04e59',
    messagingSenderId: '357054968732',
    projectId: 'movielist-f853e',
    authDomain: 'movielist-f853e.firebaseapp.com',
    storageBucket: 'movielist-f853e.appspot.com',
    measurementId: 'G-999H9925QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN17D7c0o5R3M7t5VQTbGoKQM0kXGEviU',
    appId: '1:357054968732:android:38b7968778df2a2dc04e59',
    messagingSenderId: '357054968732',
    projectId: 'movielist-f853e',
    storageBucket: 'movielist-f853e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs5K4aTWAFvWcNNj70kHl-ITcETLyuG2s',
    appId: '1:357054968732:ios:ee6b73557129fa38c04e59',
    messagingSenderId: '357054968732',
    projectId: 'movielist-f853e',
    storageBucket: 'movielist-f853e.appspot.com',
    androidClientId: '357054968732-tj2d7vnji42jan2q3ee3foj81n4idsj9.apps.googleusercontent.com',
    iosClientId: '357054968732-g2vss2rh0c0cimogrqs762db5bl3dvs8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mymovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs5K4aTWAFvWcNNj70kHl-ITcETLyuG2s',
    appId: '1:357054968732:ios:ee6b73557129fa38c04e59',
    messagingSenderId: '357054968732',
    projectId: 'movielist-f853e',
    storageBucket: 'movielist-f853e.appspot.com',
    androidClientId: '357054968732-tj2d7vnji42jan2q3ee3foj81n4idsj9.apps.googleusercontent.com',
    iosClientId: '357054968732-g2vss2rh0c0cimogrqs762db5bl3dvs8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mymovies',
  );
}
